#!/usr/bin/env node
// Season reference generator for the Gumbeaux Gators GM.
// Renders reports/season-reference-2026.md from the shared season library — a
// season-to-date baseline referenced in post-game reports. Offline; regenerate
// after the daily seed refresh.
//
//   node scripts/season-report.js            # write reports/season-reference-2026.md
//   node scripts/season-report.js --stdout   # print to stdout instead
//   node scripts/season-report.js --pdf      # branded multi-page PDF in reports/season/
//   node scripts/season-report.js --html     # branded HTML alongside (debug)

const fs = require('fs');
const path = require('path');
const S = require('./lib/season');
const { r3, r2, pct, signed, ipStr } = S;

function build() {
  const T = S.teamSummary();
  const BAT = S.batters();
  const PIT = S.pitchers();
  const TG = S.teamGameTrends();
  const updated = S.seed.rosterUpdated ? new Date(S.seed.rosterUpdated).toISOString().slice(0, 10) : '—';
  const L = [];
  const p = s => L.push(s);

  const staffIP = PIT.reduce((a, x) => a + x.outs, 0) / 3;
  const staffBB = PIT.reduce((a, x) => a + x.bb, 0);
  const staffK = PIT.reduce((a, x) => a + x.k, 0);
  const staffBB9 = staffIP ? ((staffBB * 9) / staffIP).toFixed(1) : '—';

  p('# Gumbeaux Gators — Season Reference (2026)');
  p('');
  p(`_Season-to-date baseline for post-game reports. Auto-generated by \`scripts/season-report.js\` from \`roster-seed.json\`. Stats through **${updated}** (${T.gp} games)._`);
  p('');

  p('## Team snapshot');
  p('');
  p('| | |');
  p('|---|---|');
  p(`| Record | **${T.w}-${T.l}** (${(T.w / (T.gp || 1)).toFixed(3).replace(/^0/, '')}) |`);
  p(`| Home / Away | ${T.hw}-${T.hl} home · ${T.aw}-${T.al} away |`);
  p(`| Last 10 / Last 5 | ${T.last10} / ${T.last5} |`);
  p(`| Current streak | ${T.streak} |`);
  p(`| Runs for / against | ${T.rf} / ${T.ra} (**${signed(T.diff)}** diff) |`);
  p(`| Runs per game | ${T.rpg.toFixed(1)} scored · ${T.rapg.toFixed(1)} allowed |`);
  p(`| One-run games | ${T.oneRun} |`);
  p('');

  p('## Key trends & flags');
  p('');
  const topBat = BAT.filter(b => b.pa >= 20).slice(0, 3).map(b => `${b.meta.name} (${r3(b.ops)} OPS)`).join(', ');
  const hot = BAT.filter(b => b.trend != null && b.pa >= 15 && b.trend > 0.04).sort((a, b) => b.trend - a.trend).slice(0, 3);
  const cold = BAT.filter(b => b.trend != null && b.pa >= 15 && b.trend < -0.04).sort((a, b) => a.trend - b.trend).slice(0, 3);
  p(`- **Top bats:** ${topBat || '—'}.`);
  if (hot.length) p(`- **Heating up (last 5 vs season AVG):** ${hot.map(b => `${b.meta.name} ${b.l5line}, ${S.pts(b.trend)} pts`).join('; ')}.`);
  if (cold.length) p(`- **Cooling off:** ${cold.map(b => `${b.meta.name} ${b.l5line}, ${S.pts(b.trend)} pts`).join('; ')}.`);
  p(`- **Staff command:** ${staffBB} walks vs ${staffK} K over ${staffIP.toFixed(1)} IP (${staffBB9} BB/9). Walks are the recurring run-prevention story — track team strike% each game.`);
  p(`- **Close-game record:** ${T.oneRun} in one-run games — bullpen leverage and late offense swing the season.`);
  p('');

  p('## Hitters — season lines');
  p('');
  p('Sorted by OPS. **L5** = last 5 games; **Trend** = last-5 AVG minus season AVG (▲ hot / ▼ cold). Rank = Texas Collegiate League rank.');
  p('');
  p('| # | Player | Pos | G | AVG/OBP/SLG | OPS | HR | RBI | SB | BB% | K% | L5 | Trend |');
  p('|---|---|---|--:|---|--:|--:|--:|--:|--:|--:|---|:--:|');
  BAT.forEach(b => {
    const tr = b.trend == null ? '—' : (b.trend > 0.001 ? '▲ ' : b.trend < -0.001 ? '▼ ' : '· ') + S.pts(b.trend);
    const rk = b.ranks && b.ranks.slg ? ` _(${b.ranks.slg})_` : '';
    p(`| ${b.meta.num} | ${b.meta.name} | ${b.meta.pos} | ${b.gp} | ${r3(b.avg)}/${r3(b.obp)}/${r3(b.slg)} | **${r3(b.ops)}**${rk} | ${b.hr} | ${b.rbi} | ${b.sb} | ${pct(b.bbp)} | ${pct(b.kp)} | ${b.l5line} | ${tr} |`);
  });
  p('');

  p('## Pitchers — season lines');
  p('');
  p('Sorted by innings. **Role** SP/RP/Swing from GS share. **L3** = last 3 outings. ERA shown next to last-3 ERA to flag hot/cold arms.');
  p('');
  p('| # | Pitcher | Role | App | IP | W-L | SV | ERA | WHIP | K/9 | BB/9 | K | BB | L3 IP/ERA |');
  p('|---|---|:--:|--:|--:|:--:|--:|--:|--:|--:|--:|--:|--:|---|');
  PIT.forEach(p2 => {
    const l3 = p2.l3era == null ? '—' : `${p2.l3ip} / ${r2(p2.l3era)}`;
    p(`| ${p2.meta.num} | ${p2.meta.name} | ${p2.role} | ${p2.app} | ${ipStr(p2.outs)} | ${p2.w}-${p2.l} | ${p2.sv} | ${r2(p2.era)} | ${r2(p2.whip)} | ${p2.k9 == null ? '—' : p2.k9.toFixed(1)} | ${p2.bb9 == null ? '—' : p2.bb9.toFixed(1)} | ${p2.k} | ${p2.bb} | ${l3} |`);
  });
  p('');

  p('## Game-by-game (team)');
  p('');
  p('Team batting (H/BB/K) and pitching (ER/BB/K allowed) summed from individual player game logs, with result. Use to spot scoring droughts and command spikes.');
  p('');
  p('> **Data note:** these rows are reconstructed by summing per-player logs, which refresh once daily with the seed. The **most recent game can be partial** until every player\'s log catches up (a row whose pitching IP is well under the game length is still filling in). Season lines, ranks, and the run totals above come straight from the league/player pages and are authoritative.');
  p('');
  p('| Date | Opp | Result | Bat: H-BB-K | HR | Pitch: IP-ER-BB-K |');
  p('|---|---|:--:|---|--:|---|');
  TG.forEach(g => {
    p(`| ${g.date} | ${S.oppShort(g.opp)} | ${g.score || ''} | ${g.bh}-${g.bbb}-${g.bk} | ${g.bhr} | ${ipStr(g.pip)}-${g.per}-${g.pbb}-${g.pk} |`);
  });
  p('');

  p('## Glossary (for the report)');
  p('');
  p('- **AVG / OBP / SLG** — batting average · on-base % · slugging %. **OPS** = OBP + SLG (one-number bat value; ~.750 is solid, .900+ is excellent).');
  p('- **ISO** (Isolated Power) = SLG − AVG — raw power independent of singles.');
  p('- **BB% / K%** — walk and strikeout rate per plate appearance (process/discipline).');
  p('- **L5 / L3** — totals over the last 5 games (bat) / 3 outings (pitch); the recent-form window.');
  p('- **Trend** — last-5 AVG minus season AVG, in points (▲ hot / ▼ cold). Filters small-sample noise from real swings.');
  p('- **ERA / WHIP** — earned runs per 9 IP · baserunners (H+BB) per IP. **K/9, BB/9** — strikeouts and walks per 9 IP (lower BB/9 = better command).');
  p('- **Role** — SP starter · RP reliever · SwingP both, inferred from games-started share.');
  p('');

  p('## How to use this in a post-game report');
  p('');
  p('- **Auto-generate the game report:** `node scripts/postgame-report.js latest` (or pass a `Jun 24`-style date / box id). It frames every line against the baselines above.');
  p('- **Frame each line vs. the season baseline** (e.g. "2-for-4 raises X from .250 → .268" or "the 5 BB matches a season-long command theme").');
  p('- **Cite the Trend column** to call a player genuinely hot/cold vs. small-sample noise.');
  p('- **Regenerate** after the seed refreshes: `node scripts/season-report.js`.');
  p('');

  return L.join('\n') + '\n';
}

// ---- branded HTML + PDF -----------------------------------------------------
const esc = s => String(s).replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
// Inline span formatting for the subset of Markdown this report emits.
const span = s => esc(s)
  .replace(/`([^`]+)`/g, '<code>$1</code>')
  .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
  .replace(/(^|[\s(])_([^_]+)_(?=[\s.,;:)]|$)/g, '$1<em>$2</em>');

// Minimal Markdown -> HTML for headings, tables, lists, blockquotes and
// paragraphs — enough for the season reference's structure.
function mdToHtml(src) {
  const lines = src.split('\n');
  const out = [];
  let i = 0;
  const cell = c => c.replace(/^:?-+:?$/, ''); // ignore table separator dashes
  while (i < lines.length) {
    const line = lines[i];
    if (/^\|/.test(line) && /^\|[\s:|-]+\|?\s*$/.test(lines[i + 1] || '')) {
      const head = line.split('|').slice(1, -1).map(c => c.trim());
      i += 2;
      const body = [];
      while (i < lines.length && /^\|/.test(lines[i])) { body.push(lines[i].split('|').slice(1, -1).map(c => c.trim())); i++; }
      out.push('<table><thead><tr>' + head.map(c => `<th>${span(c)}</th>`).join('') + '</tr></thead><tbody>'
        + body.map(r => '<tr>' + r.map(c => `<td>${span(cell(c))}</td>`).join('') + '</tr>').join('') + '</tbody></table>');
      continue;
    }
    if (/^### /.test(line)) { out.push(`<h3>${span(line.slice(4))}</h3>`); i++; continue; }
    if (/^## /.test(line)) { out.push(`<h2>${span(line.slice(3))}</h2>`); i++; continue; }
    if (/^# /.test(line)) { i++; continue; } // page title comes from the band header
    if (/^> /.test(line)) { out.push(`<blockquote>${span(line.slice(2))}</blockquote>`); i++; continue; }
    if (/^- /.test(line)) {
      const items = [];
      while (i < lines.length && /^- /.test(lines[i])) { items.push(`<li>${span(lines[i].slice(2))}</li>`); i++; }
      out.push('<ul>' + items.join('') + '</ul>');
      continue;
    }
    if (line.trim() === '') { i++; continue; }
    out.push(`<p>${span(line)}</p>`);
    i++;
  }
  return out.join('\n');
}

function buildHtml(md) {
  const T = S.teamSummary();
  const updated = S.seed.rosterUpdated ? new Date(S.seed.rosterUpdated).toISOString().slice(0, 10) : '—';
  const croc = S.crocSkinDataUri();
  return `<!doctype html><html><head><meta charset='utf-8'><style>
@page{size:letter;margin:0.5in;}
*{box-sizing:border-box;margin:0;padding:0;}
html{-webkit-print-color-adjust:exact;print-color-adjust:exact;}
body{font-family:Georgia,'Times New Roman',serif;color:#1b1e27;font-size:11px;line-height:1.5;}
.band{display:flex;align-items:center;gap:16px;color:#fff;padding:16px 20px;border-radius:12px;border:2px solid #ecc913;
background:linear-gradient(rgba(22,16,43,.02),rgba(22,16,43,.16))${croc ? `,url('${croc}') center center / cover no-repeat` : ''};
background-color:#3a2480;box-shadow:0 4px 14px rgba(58,36,128,.3),inset 0 0 0 1px rgba(255,255,255,.08);}
.band img{width:58px;height:58px;}
.k{font-family:'Helvetica Neue',Arial,sans-serif;font-size:10px;letter-spacing:.2em;text-transform:uppercase;color:#ffd633;font-weight:800;text-shadow:0 1px 2px rgba(0,0,0,.5);}
.band h1{font-family:'Helvetica Neue',Arial,sans-serif;font-size:24px;font-weight:900;line-height:1.08;margin:2px 0;text-shadow:0 2px 4px rgba(0,0,0,.55);}
.band .sub{font-family:Arial,sans-serif;font-size:11px;font-weight:700;color:#efe7ff;text-shadow:0 1px 2px rgba(0,0,0,.5);}
.band .rec{margin-left:auto;text-align:center;font-family:'Helvetica Neue',Arial,sans-serif;}
.band .rec b{display:block;font-size:22px;font-weight:900;}
.band .rec span{font-size:9px;letter-spacing:.1em;text-transform:uppercase;color:#efe7ff;}
h2{font-family:'Helvetica Neue',Arial,sans-serif;font-size:12.5px;text-transform:uppercase;letter-spacing:.08em;color:#714ad2;font-weight:800;border-bottom:2px solid #714ad2;padding-bottom:4px;margin:18px 0 8px;break-after:avoid;}
h3{font-family:'Helvetica Neue',Arial,sans-serif;font-size:11px;color:#3a2480;margin:10px 0 4px;}
p{margin:6px 0;}
ul{list-style:none;margin:6px 0;}
li{position:relative;padding:4px 0 4px 15px;border-bottom:1px solid #eee;}
li:last-child{border-bottom:none;}
li:before{content:'';position:absolute;left:0;top:9px;width:6px;height:6px;border-radius:2px;background:#714ad2;}
blockquote{background:#f7f4fd;border-left:3px solid #714ad2;color:#4a3b6e;padding:7px 11px;margin:8px 0;font-family:Arial,sans-serif;font-size:9.5px;}
table{width:100%;border-collapse:collapse;margin:6px 0 12px;font-family:'Helvetica Neue',Arial,sans-serif;font-size:9px;break-inside:auto;}
th{background:linear-gradient(180deg,#714ad2,#4e3191);color:#fff;font-size:8.5px;letter-spacing:.04em;text-transform:uppercase;padding:5px 5px;text-align:left;}
td{padding:4px 5px;border-bottom:1px solid #ece7f6;}
tr:nth-child(even) td{background:#f7f4fd;}
code{font-family:'SF Mono',Consolas,monospace;font-size:9px;background:#efeaf9;padding:1px 4px;border-radius:3px;color:#4e3191;}
strong{color:#3a2480;}
</style></head><body>
<div class='band'><img src='${S.gatorsLogoDataUri()}'><div><div class='k'>Gumbeaux Gators · GM Season Reference</div><h1>Season Reference — 2026</h1><div class='sub'>Through ${esc(updated)} · ${T.gp} games</div></div><div class='rec'><b>${T.w}–${T.l}</b><span>Record</span></div></div>
${mdToHtml(md)}
</body></html>`;
}

function findChromium() {
  const cands = [process.env.CHROMIUM_PATH, process.env.PUPPETEER_EXECUTABLE_PATH,
    '/opt/pw-browsers/chromium', '/usr/bin/chromium', '/usr/bin/chromium-browser', '/usr/bin/google-chrome'].filter(Boolean);
  for (const c of cands) { try { if (fs.existsSync(c)) return c; } catch (e) {} }
  try { const base = process.env.PLAYWRIGHT_BROWSERS_PATH || '/opt/pw-browsers'; for (const d of fs.readdirSync(base)) { const pth = path.join(base, d, 'chrome-linux', 'chrome'); if (fs.existsSync(pth)) return pth; } } catch (e) {}
  return null;
}

function renderPdf(html, outPath) {
  const bin = findChromium();
  const tmp = outPath.replace(/\.pdf$/, '') + '.tmp.html';
  fs.writeFileSync(tmp, html);
  if (!bin) { console.error('No Chromium found for --pdf. Set CHROMIUM_PATH. HTML left at ' + tmp); return false; }
  try {
    require('child_process').execFileSync(bin,
      ['--headless=new', '--no-sandbox', '--disable-gpu', '--no-pdf-header-footer', `--print-to-pdf=${outPath}`, 'file://' + path.resolve(tmp)],
      { stdio: 'ignore' });
    fs.unlinkSync(tmp);
    return true;
  } catch (e) { console.error('Chromium PDF render failed:', e.message, '\nHTML left at ' + tmp); return false; }
}

const md = build();
const PDF = process.argv.includes('--pdf');
const HTML = process.argv.includes('--html');
if (process.argv.includes('--stdout')) {
  process.stdout.write(md);
} else if (PDF || HTML) {
  const dir = path.join(__dirname, '..', 'reports', 'season');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const html = buildHtml(md);
  if (HTML) { const hf = path.join(dir, 'season-reference-2026.html'); fs.writeFileSync(hf, html); console.error('wrote', path.relative(path.join(__dirname, '..'), hf)); }
  if (PDF) { const out = path.join(dir, 'season-reference-2026.pdf'); if (renderPdf(html, out)) console.log('wrote', path.relative(path.join(__dirname, '..'), out)); }
} else {
  const dir = path.join(__dirname, '..', 'reports');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, 'season-reference-2026.md');
  fs.writeFileSync(file, md);
  console.log('wrote', path.relative(path.join(__dirname, '..'), file), `(${md.length} bytes)`);
}
