#!/usr/bin/env node
// Season reference generator for the Gumbeaux Gators GM.
// Renders reports/season-reference-2026.md from the shared season library — a
// season-to-date baseline referenced in post-game reports. Offline; regenerate
// after the daily seed refresh.
//
//   node scripts/season-report.js            # write reports/season-reference-2026.md
//   node scripts/season-report.js --stdout   # print to stdout instead

const fs = require('fs');
const path = require('path');
const S = require('./lib/season');
const { r3, r2, pct, signed, ipStr } = S;

function build() {
  const T = S.teamSummary();
  const BAT = S.batters();
  const PIT = S.pitchers();
  const TG = S.teamGameTrends();
  const updated = S.seed.rosterUpdated ? new Date(S.seed.rosterUpdated).toISOString().slice(0, 10) : '—';
  const L = [];
  const p = s => L.push(s);

  const staffIP = PIT.reduce((a, x) => a + x.outs, 0) / 3;
  const staffBB = PIT.reduce((a, x) => a + x.bb, 0);
  const staffK = PIT.reduce((a, x) => a + x.k, 0);
  const staffBB9 = staffIP ? ((staffBB * 9) / staffIP).toFixed(1) : '—';

  p('# Gumbeaux Gators — Season Reference (2026)');
  p('');
  p(`_Season-to-date baseline for post-game reports. Auto-generated by \`scripts/season-report.js\` from \`roster-seed.json\`. Stats through **${updated}** (${T.gp} games)._`);
  p('');

  p('## Team snapshot');
  p('');
  p('| | |');
  p('|---|---|');
  p(`| Record | **${T.w}-${T.l}** (${(T.w / (T.gp || 1)).toFixed(3).replace(/^0/, '')}) |`);
  p(`| Home / Away | ${T.hw}-${T.hl} home · ${T.aw}-${T.al} away |`);
  p(`| Last 10 / Last 5 | ${T.last10} / ${T.last5} |`);
  p(`| Current streak | ${T.streak} |`);
  p(`| Runs for / against | ${T.rf} / ${T.ra} (**${signed(T.diff)}** diff) |`);
  p(`| Runs per game | ${T.rpg.toFixed(1)} scored · ${T.rapg.toFixed(1)} allowed |`);
  p(`| One-run games | ${T.oneRun} |`);
  p('');

  p('## Key trends & flags');
  p('');
  const topBat = BAT.filter(b => b.pa >= 20).slice(0, 3).map(b => `${b.meta.name} (${r3(b.ops)} OPS)`).join(', ');
  const hot = BAT.filter(b => b.trend != null && b.pa >= 15 && b.trend > 0.04).sort((a, b) => b.trend - a.trend).slice(0, 3);
  const cold = BAT.filter(b => b.trend != null && b.pa >= 15 && b.trend < -0.04).sort((a, b) => a.trend - b.trend).slice(0, 3);
  p(`- **Top bats:** ${topBat || '—'}.`);
  if (hot.length) p(`- **Heating up (last 5 vs season AVG):** ${hot.map(b => `${b.meta.name} ${b.l5line}, ${S.pts(b.trend)} pts`).join('; ')}.`);
  if (cold.length) p(`- **Cooling off:** ${cold.map(b => `${b.meta.name} ${b.l5line}, ${S.pts(b.trend)} pts`).join('; ')}.`);
  p(`- **Staff command:** ${staffBB} walks vs ${staffK} K over ${staffIP.toFixed(1)} IP (${staffBB9} BB/9). Walks are the recurring run-prevention story — track team strike% each game.`);
  p(`- **Close-game record:** ${T.oneRun} in one-run games — bullpen leverage and late offense swing the season.`);
  p('');

  p('## Hitters — season lines');
  p('');
  p('Sorted by OPS. **L5** = last 5 games; **Trend** = last-5 AVG minus season AVG (▲ hot / ▼ cold). Rank = Texas Collegiate League rank.');
  p('');
  p('| # | Player | Pos | G | AVG/OBP/SLG | OPS | HR | RBI | SB | BB% | K% | L5 | Trend |');
  p('|---|---|---|--:|---|--:|--:|--:|--:|--:|--:|---|:--:|');
  BAT.forEach(b => {
    const tr = b.trend == null ? '—' : (b.trend > 0.001 ? '▲ ' : b.trend < -0.001 ? '▼ ' : '· ') + S.pts(b.trend);
    const rk = b.ranks && b.ranks.slg ? ` _(${b.ranks.slg})_` : '';
    p(`| ${b.meta.num} | ${b.meta.name} | ${b.meta.pos} | ${b.gp} | ${r3(b.avg)}/${r3(b.obp)}/${r3(b.slg)} | **${r3(b.ops)}**${rk} | ${b.hr} | ${b.rbi} | ${b.sb} | ${pct(b.bbp)} | ${pct(b.kp)} | ${b.l5line} | ${tr} |`);
  });
  p('');

  p('## Pitchers — season lines');
  p('');
  p('Sorted by innings. **Role** SP/RP/Swing from GS share. **L3** = last 3 outings. ERA shown next to last-3 ERA to flag hot/cold arms.');
  p('');
  p('| # | Pitcher | Role | App | IP | W-L | SV | ERA | WHIP | K/9 | BB/9 | K | BB | L3 IP/ERA |');
  p('|---|---|:--:|--:|--:|:--:|--:|--:|--:|--:|--:|--:|--:|---|');
  PIT.forEach(p2 => {
    const l3 = p2.l3era == null ? '—' : `${p2.l3ip} / ${r2(p2.l3era)}`;
    p(`| ${p2.meta.num} | ${p2.meta.name} | ${p2.role} | ${p2.app} | ${ipStr(p2.outs)} | ${p2.w}-${p2.l} | ${p2.sv} | ${r2(p2.era)} | ${r2(p2.whip)} | ${p2.k9 == null ? '—' : p2.k9.toFixed(1)} | ${p2.bb9 == null ? '—' : p2.bb9.toFixed(1)} | ${p2.k} | ${p2.bb} | ${l3} |`);
  });
  p('');

  p('## Game-by-game (team)');
  p('');
  p('Team batting (H/BB/K) and pitching (ER/BB/K allowed) summed from individual player game logs, with result. Use to spot scoring droughts and command spikes.');
  p('');
  p('> **Data note:** these rows are reconstructed by summing per-player logs, which refresh once daily with the seed. The **most recent game can be partial** until every player\'s log catches up (a row whose pitching IP is well under the game length is still filling in). Season lines, ranks, and the run totals above come straight from the league/player pages and are authoritative.');
  p('');
  p('| Date | Opp | Result | Bat: H-BB-K | HR | Pitch: IP-ER-BB-K |');
  p('|---|---|:--:|---|--:|---|');
  TG.forEach(g => {
    p(`| ${g.date} | ${S.oppShort(g.opp)} | ${g.score || ''} | ${g.bh}-${g.bbb}-${g.bk} | ${g.bhr} | ${ipStr(g.pip)}-${g.per}-${g.pbb}-${g.pk} |`);
  });
  p('');

  p('## Glossary (for the report)');
  p('');
  p('- **AVG / OBP / SLG** — batting average · on-base % · slugging %. **OPS** = OBP + SLG (one-number bat value; ~.750 is solid, .900+ is excellent).');
  p('- **ISO** (Isolated Power) = SLG − AVG — raw power independent of singles.');
  p('- **BB% / K%** — walk and strikeout rate per plate appearance (process/discipline).');
  p('- **L5 / L3** — totals over the last 5 games (bat) / 3 outings (pitch); the recent-form window.');
  p('- **Trend** — last-5 AVG minus season AVG, in points (▲ hot / ▼ cold). Filters small-sample noise from real swings.');
  p('- **ERA / WHIP** — earned runs per 9 IP · baserunners (H+BB) per IP. **K/9, BB/9** — strikeouts and walks per 9 IP (lower BB/9 = better command).');
  p('- **Role** — SP starter · RP reliever · SwingP both, inferred from games-started share.');
  p('');

  p('## How to use this in a post-game report');
  p('');
  p('- **Auto-generate the game report:** `node scripts/postgame-report.js latest` (or pass a `Jun 24`-style date / box id). It frames every line against the baselines above.');
  p('- **Frame each line vs. the season baseline** (e.g. "2-for-4 raises X from .250 → .268" or "the 5 BB matches a season-long command theme").');
  p('- **Cite the Trend column** to call a player genuinely hot/cold vs. small-sample noise.');
  p('- **Regenerate** after the seed refreshes: `node scripts/season-report.js`.');
  p('');

  return L.join('\n') + '\n';
}

const md = build();
if (process.argv.includes('--stdout')) {
  process.stdout.write(md);
} else {
  const dir = path.join(__dirname, '..', 'reports');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, 'season-reference-2026.md');
  fs.writeFileSync(file, md);
  console.log('wrote', path.relative(path.join(__dirname, '..'), file), `(${md.length} bytes)`);
}
